remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Elias Frühwein
description: Incoming student of MSc in Data Science 

markdown: kramdown
mathjax: true
